apstack-mysql:
  image: mysql:5.6
  volumes:
    - /Users/chk/docker/webstack/mysql:/var/lib/mysql
    - /Users/chk/docker/apstack/conf/mysql:/etc/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=MyMysql2RootPassword
    - MYSQL_USER=craft3
    - MYSQL_PASSWORD=aprixoDBPass2
    - MYSQL_DATABASE=craft3
  restart: "always"
  expose:
    - 3307
    - 3306
  # disabled as default for public access
  ports:
    - "3307:3307"
    - "3306:3306"

#apstack-elastic:
#    image: elasticsearch:latest
#    volumes:
#      -  /Users/chk/docker/webstack/elasticsearch/data:/usr/share/elasticsearch/data
#    restart: "always"
#    expose:
#      - 9200
#      - 9300

apstack-memcached:
    image: memcached:latest
    restart: "always"
    expose:
      - 11211


apstack-php-fpm:
  build: phpstack
  links:
    - apstack-mysql
    - apstack-memcached
  expose:
    - 9000
  restart: "always"
  volumes:
#    - /srv/docker/webstack/www:/var/www             # nginx default webroot directory
    - /Users/chk/projects:/Users/chk/projects                # this is used, if you want to use a home directory for development

    #- /Users/chk/projects:/srv/www/vhost              # Defult Webhost structure (I prefer this)
    - /Users/chk/docker/apstack/conf/php:/usr/local/etc  # nginx configuration (default)
    - /Users/chk/docker/tmp:/tmp # debug Trace?

apstack-nginx:
   image: nginx:latest
   restart: "always"
   volumes:
    - /Users/chk/projects/:/Users/chk/projects/                # this is used, if you want to use a home directory for development
    #- /Users/chk/projects:/srv/www/vhost              # Defult Webhost structure (I prefer this)
    - /Users/chk/docker/apstack/conf/nginx:/etc/nginx  # nginx configuration (default)
   links:
     - apstack-php-fpm
   ports:
    - "80:80"
    - "443:443"
