apstack-mysql:
  image: mysql:latest
  volumes:
    - /srv/docker/webstack/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=MyMysql2RootPassword
    - MYSQL_USER=aprixo
    - MYSQL_PASSWORD=aprixoDBPass2
    - MYSQL_DATABASE=aprixo
  restart: "always"
  expose:
    - "3307"
apstack-mongo:
  image: mongo:latest
  volumes:
    - /srv/docker/webstack/mongo:/var/lib/mongo
  restart: "always"
apstack-elastic:
    image: elasticsearch:latest
    volumes:
    -  /srv/docker/webstack/elasticsearch/data:/usr/share/elasticsearch/data
    restart: "always"
    expose:
    - "9200"
    - "9300"
apstack-php-fpm:
  build: phpstack
  links:
    - apstack-mysql
    - apstack-mongo
    - apstack-elastic
  expose:
    - "9000"
  restart: "always"
  volumes:
#    - /srv/docker/webstack/www:/var/www
    - /home:/home
    - /srv/www/vhost:/srv/www/vhost

apstack-nginx:
   image: nginx:latest
   restart: "always"
   volumes:
#    - /srv/docker/webstack/www:/var/www
    - /home:/home
    - /srv/www/vhost:/srv/www/vhost
    - /srv/www/conf/nginx:/etc/nginx
   links:
     - apstack-php-fpm

   ports:
    - "80:80"
    - "443:443"
