FROM php:7.1-fpm
LABEL Description = "general state of the art php plattform with multisite support" VENDOR="Christian Kiesewalter"

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        libcurl4-gnutls-dev \
        libxml2-dev\
        openssl \
        libssl-dev \
        libicu-dev \
        git
  RUN  docker-php-ext-install -j$(nproc) iconv mcrypt
  RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install -j$(nproc) curl \
    && docker-php-ext-install -j$(nproc) zip \
    && docker-php-ext-install -j$(nproc) soap
  RUN docker-php-ext-install -j$(nproc) pdo \
    && docker-php-ext-install -j$(nproc) pdo_mysql \
    && docker-php-ext-install -j$(nproc) mysqli \
    && docker-php-ext-install -j$(nproc) opcache
    RUN docker-php-ext-install -j$(nproc) intl

RUN apt-get update && apt-get install -y libmemcached-dev \
    && pecl install memcached \
    && docker-php-ext-enable memcached

RUN pecl install xdebug && docker-php-ext-enable xdebug


EXPOSE 9000



